name: develop push
on:
  push:
    branches: [develop]

jobs:
  build:
    name: build and test on ubuntu-18.04
    runs-on: ubuntu-18.04
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore

      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase="${{ secrets.GPG_SECRET }}" --output ./WereldService/appsettings.json --decrypt ./WereldService/appsettings.json.gpg

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

      - name: Publish
        run: dotnet publish -c Release -o out

      - name: Upload release artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-artifact
          path: ./out

      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v1
        with:
          name: dockerfile-artifact
          path: ./Dockerfile

  delivery:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v1
        with:
          name: release-artifact
          path: .
      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v1
        with:
          name: dockerfile-artifact
          path: .
      - name: Deliver Docker image
        env:
          CONTAINER_IMAGE: ${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:${{ github.sha }}
          CONTAINER_IMAGE_LATEST: ${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:develop
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
          docker push $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE_LATEST